import math
angle_deg = float(input("enter angle in degrees: "))
angle_rad = math.radians(angle_deg)
sin_val = math.sin(angle_rad)
cos_val = math.cos(angle_rad)
tan_val = math.tan(angle_rad)
print(f"\nAngle: {angle_deg}")
print(f"sin({angle_deg}) = {sin_val:.4f}")
print(f"cos({angle_deg}) = {cos_val:.4f}")
print(f"tan({angle_deg}) = {tan_val:.4f}")